analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gr.dart"
    - "**/*.iconfig.dart"
    - "**/generated_plugin_registrant.dart"
    - "**/*generated_plugin_registrant.dart"
    - '**/app_localizations*.dart'


linter:
  rules:
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables