name: TMDB

packages:
  - packages/*
  - apps/*

scripts:
  lint_all:
    run: melos run format && melos run analyze
    description: Run all static analysis checks.


  analyze:
    # We are setting the concurrency to 1 because a higher concurrency can crash
    # the analysis server on low performance machines (like GitHub Actions).
    run: |
      melos exec -c 1 -- \
        dart analyze . --fatal-infos
    description: |
      Run `dart analyze` in all packages.
       - Note: you can also rely on your IDEs Dart Analysis / Issues window.

  format:
    run: |
      dart pub global run flutter_plugin_tools format
    description: |
      Formats the code of all packages (Java, Objective-C, and Dart).
       - Requires `flutter_plugin_tools` (`pub global activate flutter_plugin_tools`).
       - Requires `git`.
       - Requires `clang-format` (can be installed via Brew on MacOS).


  generate_files:
    exec: dart run build_runner build --delete-conflicting-outputs
    packageFilters:
      dependsOn: build_runner
    description: dart run build_runner build --delete-conflicting-outputs


  localizations:
    exec: flutter gen-l10n
    packageFilters:
      dependsOn: intl
    description: generate localizations files

  clean:
    exec: flutter clean
    description: Cleaning whole flutter project


