#file: noinspection DartPathPackageReference
name: tmdb_app
description: "TMDD Application"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.3
  retrofit: ^4.0.3
  dio: ^5.4.0
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
  get_it: ^7.6.7
  go_router: ^12.1.3
  json_annotation: ^4.8.1
  fpdart: ^1.1.0
  equatable: ^2.0.5
  google_fonts: ^6.1.0
  responsive_framework: ^1.1.1
  extended_image: ^8.2.0
  pretty_dio_logger: ^1.3.1
  image_network: ^2.5.4+1
  infinite_scroll_pagination: ^4.0.0
  common_widgets:
    path: ../../packages/common_widgets


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  retrofit_generator: ^8.0.6
  build_runner: ^2.4.8
  json_serializable: ^6.7.1



flutter:
  uses-material-design: true
