import "package:common_widgets/theme/app_colors.dart";
import "package:flutter/material.dart";

final darkTheme = ThemeData.dark(useMaterial3: true).copyWith(
  brightness: Brightness.dark,
  colorScheme: darkColorScheme,
  textTheme: darkTextTheme,
);

final lightTheme = ThemeData.light(useMaterial3: true).copyWith(
  brightness: Brightness.light,
  colorScheme: lightColorScheme,
  textTheme: lightTextTheme,
);

final TextTheme lightTextTheme = const TextTheme(
  bodyLarge: TextStyle(
    color: Colors.black,
    decoration: TextDecoration.none,
    fontFamily: "PoppinsRegular",
    fontSize: 16.0,
    fontWeight: FontWeight.w400,
    letterSpacing: 0.15,
    textBaseline: TextBaseline.alphabetic,
  ),
  bodyMedium: TextStyle(
    color: Colors.black,
    decoration: TextDecoration.none,
    fontFamily: "PoppinsRegular",
    fontSize: 14.0,
    fontWeight: FontWeight.w400,
    letterSpacing: 0.25,
    textBaseline: TextBaseline.alphabetic,
  ),
  bodySmall: TextStyle(
    color: Colors.black,
    decoration: TextDecoration.none,
    fontFamily: "PoppinsRegular",
    fontSize: 12.0,
    fontWeight: FontWeight.w400,
    letterSpacing: 0.4,
    textBaseline: TextBaseline.alphabetic,
  ),
  displayLarge: TextStyle(
    color: Colors.black,
    decoration: TextDecoration.none,
    fontFamily: 'Poppins_300',
    fontSize: 57.0,
    fontWeight: FontWeight.w300,
    letterSpacing: 0,
    textBaseline: TextBaseline.alphabetic,
  ),
  displayMedium: TextStyle(
    color: Colors.black,
    decoration: TextDecoration.none,
    fontFamily: 'Poppins_300',
    fontSize: 45.0,
    fontWeight: FontWeight.w300,
    letterSpacing: 0,
    textBaseline: TextBaseline.alphabetic,
  ),
  displaySmall: TextStyle(
    color: Colors.black,
    decoration: TextDecoration.none,
    fontFamily: "PoppinsRegular",
    fontSize: 36.0,
    fontWeight: FontWeight.w400,
    letterSpacing: 0,
    textBaseline: TextBaseline.alphabetic,
  ),
  headlineLarge: TextStyle(
    color: Colors.black,
    decoration: TextDecoration.none,
    fontFamily: "PoppinsRegular",
    fontSize: 32.0,
    fontWeight: FontWeight.w400,
    letterSpacing: 0,
    textBaseline: TextBaseline.alphabetic,
  ),
  headlineMedium: TextStyle(
    color: Colors.black,
    decoration: TextDecoration.none,
    fontFamily: "PoppinsRegular",
    fontSize: 28.0,
    fontWeight: FontWeight.w400,
    letterSpacing: 0,
    textBaseline: TextBaseline.alphabetic,
  ),
  headlineSmall: TextStyle(
    color: Colors.black,
    decoration: TextDecoration.none,
    fontFamily: "PoppinsRegular",
    fontSize: 24.0,
    fontWeight: FontWeight.w400,
    letterSpacing: 0,
    textBaseline: TextBaseline.alphabetic,
  ),
  labelLarge: TextStyle(
    color: Colors.black,
    decoration: TextDecoration.none,
    fontFamily: "PoppinsMedium",
    fontSize: 14.0,
    fontWeight: FontWeight.w500,
    letterSpacing: 0.1,
    textBaseline: TextBaseline.alphabetic,
  ),
  labelMedium: TextStyle(
    color: Colors.black,
    decoration: TextDecoration.none,
    fontFamily: "PoppinsMedium",
    fontSize: 12.0,
    fontWeight: FontWeight.w400,
    letterSpacing: 0.5,
    textBaseline: TextBaseline.alphabetic,
  ),
  labelSmall: TextStyle(
    color: Colors.black,
    decoration: TextDecoration.none,
    fontFamily: "PoppinsMedium",
    fontSize: 11.0,
    fontWeight: FontWeight.w400,
    letterSpacing: 0.5,
    textBaseline: TextBaseline.alphabetic,
  ),
  titleLarge: TextStyle(
    color: Colors.black,
    decoration: TextDecoration.none,
    fontFamily: "PoppinsMedium",
    fontSize: 22.0,
    fontWeight: FontWeight.w500,
    letterSpacing: 0,
    textBaseline: TextBaseline.alphabetic,
  ),
  titleMedium: TextStyle(
    color: Colors.black,
    decoration: TextDecoration.none,
    fontFamily: "PoppinsMedium",
    fontSize: 16.0,
    fontWeight: FontWeight.w400,
    letterSpacing: 0.15,
    textBaseline: TextBaseline.alphabetic,
  ),
  titleSmall: TextStyle(
    color: Colors.black,
    decoration: TextDecoration.none,
    fontFamily: "PoppinsMedium",
    fontSize: 14.0,
    fontWeight: FontWeight.w500,
    letterSpacing: 0.1,
    textBaseline: TextBaseline.alphabetic,
  ),
);

final TextTheme darkTextTheme = const TextTheme(
  bodyLarge: TextStyle(
    color: Colors.white,
    decoration: TextDecoration.none,
    fontFamily: "PoppinsRegular",
    fontSize: 16.0,
    fontWeight: FontWeight.w400,
    letterSpacing: 0.15,
    textBaseline: TextBaseline.alphabetic,
  ),
  bodyMedium: TextStyle(
    color: Colors.white,
    decoration: TextDecoration.none,
    fontFamily: "PoppinsRegular",
    fontSize: 14.0,
    fontWeight: FontWeight.w400,
    letterSpacing: 0.25,
    textBaseline: TextBaseline.alphabetic,
  ),
  bodySmall: TextStyle(
    color: Colors.white,
    decoration: TextDecoration.none,
    fontFamily: "PoppinsRegular",
    fontSize: 12.0,
    fontWeight: FontWeight.w400,
    letterSpacing: 0.4,
    textBaseline: TextBaseline.alphabetic,
  ),
  displayLarge: TextStyle(
    color: Colors.white,
    decoration: TextDecoration.none,
    fontFamily: 'Poppins_300',
    fontSize: 57.0,
    fontWeight: FontWeight.w300,
    letterSpacing: 0,
    textBaseline: TextBaseline.alphabetic,
  ),
  displayMedium: TextStyle(
    color: Colors.white,
    decoration: TextDecoration.none,
    fontFamily: 'Poppins_300',
    fontSize: 45.0,
    fontWeight: FontWeight.w300,
    letterSpacing: 0,
    textBaseline: TextBaseline.alphabetic,
  ),
  displaySmall: TextStyle(
    color: Colors.white,
    decoration: TextDecoration.none,
    fontFamily: "PoppinsRegular",
    fontSize: 36.0,
    fontWeight: FontWeight.w400,
    letterSpacing: 0,
    textBaseline: TextBaseline.alphabetic,
  ),
  headlineLarge: TextStyle(
    color: Colors.white,
    decoration: TextDecoration.none,
    fontFamily: "PoppinsRegular",
    fontSize: 32.0,
    fontWeight: FontWeight.w400,
    letterSpacing: 0,
    textBaseline: TextBaseline.alphabetic,
  ),
  headlineMedium: TextStyle(
    color: Colors.white,
    decoration: TextDecoration.none,
    fontFamily: "PoppinsRegular",
    fontSize: 28.0,
    fontWeight: FontWeight.w400,
    letterSpacing: 0,
    textBaseline: TextBaseline.alphabetic,
  ),
  headlineSmall: TextStyle(
    color: Colors.white,
    decoration: TextDecoration.none,
    fontFamily: "PoppinsRegular",
    fontSize: 24.0,
    fontWeight: FontWeight.w400,
    letterSpacing: 0,
    textBaseline: TextBaseline.alphabetic,
  ),
  labelLarge: TextStyle(
    color: Colors.white,
    decoration: TextDecoration.none,
    fontFamily: "PoppinsMedium",
    fontSize: 14.0,
    fontWeight: FontWeight.w500,
    letterSpacing: 0.1,
    textBaseline: TextBaseline.alphabetic,
  ),
  labelMedium: TextStyle(
    color: Colors.white,
    decoration: TextDecoration.none,
    fontFamily: "PoppinsMedium",
    fontSize: 12.0,
    fontWeight: FontWeight.w400,
    letterSpacing: 0.5,
    textBaseline: TextBaseline.alphabetic,
  ),
  labelSmall: TextStyle(
    color: Colors.white,
    decoration: TextDecoration.none,
    fontFamily: "PoppinsMedium",
    fontSize: 11.0,
    fontWeight: FontWeight.w400,
    letterSpacing: 0.5,
    textBaseline: TextBaseline.alphabetic,
  ),
  titleLarge: TextStyle(
    color: Colors.white,
    decoration: TextDecoration.none,
    fontFamily: "PoppinsMedium",
    fontSize: 22.0,
    fontWeight: FontWeight.w500,
    letterSpacing: 0,
    textBaseline: TextBaseline.alphabetic,
  ),
  titleMedium: TextStyle(
    color: Colors.white,
    decoration: TextDecoration.none,
    fontFamily: "PoppinsMedium",
    fontSize: 16.0,
    fontWeight: FontWeight.w400,
    letterSpacing: 0.15,
    textBaseline: TextBaseline.alphabetic,
  ),
  titleSmall: TextStyle(
    color: Colors.white,
    decoration: TextDecoration.none,
    fontFamily: "PoppinsMedium",
    fontSize: 14.0,
    fontWeight: FontWeight.w500,
    letterSpacing: 0.1,
    textBaseline: TextBaseline.alphabetic,
  ),
);
