name: common_widgets
description: "All Common widgets and fonts and all images will reside here"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.9
  lottie: ^3.0.0
  logger: ^2.0.2+1
  intl: ^0.18.1
  youtube_player_iframe: ^4.0.4
  google_fonts: ^6.1.0
  responsive_framework: ^1.1.1
  super_tooltip: ^2.0.7
  flutter_rating_bar: ^4.0.1
  url_launcher: ^6.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  flutter_gen_runner: ^5.4.0


flutter_gen:
  integrations:
    flutter_svg: true
    lottie: true

  assets:
    enabled: true

    output:
      class_name: AppAsset
      package_parameter_enabled: true
      style: camel-case


flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/images/
